import Head from "next/head";
import { Inter } from "@next/font/google";
import React, { useState } from "react";
import { GetStaticProps } from "next";
import prisma from "../lib/prisma";
import Event, { EventProps } from "../components/Event";
import Image from "next/image";
import themeImg from "../public/static/skerries-windmill.jpg";
import { useRouter } from "next/router";
import { MdArrowForwardIos, MdArrowBackIos } from "react-icons/md";

const inter = Inter({ subsets: ["latin"] });

export const getStaticProps: GetStaticProps = async () => {
  let feed = await prisma.event.findMany({
    where: {
      published: true,
      eventDate: {
        gte: new Date(),
      },
    },
    include: {
      author: {
        select: { name: true },
      },
    },
    orderBy: {
      eventDate: "asc",
    },
  });
  feed = JSON.parse(JSON.stringify(feed));
  return {
    props: { feed },
    revalidate: 10,
  };
};

type Props = {
  feed: EventProps[];
};

const Events: React.FC<Props> = (props) => {
  const router = useRouter();
  const handleBackClick = (e) => {
    e.preventDefault();
    router.push("/");
  };
  return (
    <div className="relative">
      <Head>
        <title>Skez Machine</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="robots" content="noindex"></meta>
      </Head>

      <div className="absolute z-50 top-4 left-4 md:top-8 md:left-8 text-3xl text-slate-100">
        <a href="/" onClick={handleBackClick}>
          <MdArrowBackIos />
        </a>
      </div>
      <div className="relative pb-4">
        <Image
          className="z-0 absolute w-full h-full object-cover"
          src={themeImg}
          quality={50}
          loading="eager"
          alt="Skerries Rules"
        />
        <div className="absolute z-10  w-full h-full bg-gradient-to-b from-transparent to-black"></div>
        <div className="relative pt-36 pb-6 px-6 z-20">
          <h1 className="text-3xl md:text-6xl text-slate-100 text-center">
            What's On in Skerries
          </h1>
        </div>
      </div>
      <div className="relative w-full pb-16 bg-slate-50">
        <div className="relative -mt-4 container max-w-5xl mx-auto z-50">
          <div className="flex flex-col md:flex-row md:space-between px-4">
            <div className="grow">
              {props.feed.map((event, index) => (
                <div key={index} className="mb-2">
                  <Event event={event} />
                </div>
              ))}
            </div>
            <div className="relative md:w-[380px] drop-shadow">
              <div className="w-full p-4 mb-2 ml-2 bg-white rounded-md">
                <h2 className="text-2xl mb-4 font-semibold text-center">
                  FILTER BY CATEGORY
                </h2>
                <ul className="text-sky-700">
                  <li className="flex justify-between px-4 py-2 border-b border-slate-400">
                    <div className="font-semibold">All Events</div>
                    <div className="flex justify-center items-center text-sky-700">
                      <MdArrowForwardIos />
                    </div>
                  </li>
                  <li className="flex justify-between px-4 py-2 border-b border-slate-400">
                    <div className="font-semibold">Music</div>
                    <div className="flex justify-center items-center text-sky-700">
                      <MdArrowForwardIos />
                    </div>
                  </li>
                  <li className="flex justify-between px-4 py-2 border-b border-slate-400">
                    <div className="font-semibold">Sports</div>
                    <div className="flex justify-center items-center text-sky-700">
                      <MdArrowForwardIos />
                    </div>
                  </li>
                  <li className="flex justify-between px-4 py-2 border-b border-slate-400">
                    <div className="font-semibold">Satanism</div>
                    <div className="flex justify-center items-center text-sky-700">
                      <MdArrowForwardIos />
                    </div>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Events;
