// pages/drafts.tsx

import Head from "next/head";
import { GetServerSideProps } from "next";
import { useSession, getSession } from "next-auth/react";
import Link from "next/link";
import Event, { EventProps } from "../components/Event";
import prisma from "../lib/prisma";
import Header from "@/components/Header";
import Router from "next/router";

export const getServerSideProps: GetServerSideProps = async ({ req, res }) => {
  const session = await getSession({ req });
  if (!session) {
    res.statusCode = 403;
    return { props: { drafts: [] } };
  }

  let drafts = await prisma.event.findMany({
    orderBy: {
      eventDate: "asc",
    },
  });
  drafts = JSON.parse(JSON.stringify(drafts));
  return {
    props: { drafts },
  };
};

type Props = {
  drafts: EventProps[];
};

async function publishPost(id: string): Promise<void> {
  await fetch(`/api/publish/event/${id}`, {
    method: "PUT",
  });
  Router.reload();
}

async function deletePost(id: string): Promise<void> {
  await fetch(`/api/event/${id}`, {
    method: "DELETE",
  });
  Router.reload();
}

const duplicateEvent = async (event) => {
  try {
    const body = {
      title: event.title,
      category: event.category,
      content: event.content,
      venue: event.venue,
      address: event.address,
      eventDate: event.eventDate,
      eventTime: event.eventTime,
      linkUrl: event.linkUrl,
      linkDesc: event.linkUrl,
    };
    await fetch("/api/event/duplicate", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(body),
    });
    await Router.reload();
  } catch (error) {
    console.error(error);
  }
};

const Drafts: React.FC<Props> = (props) => {
  const { data: session } = useSession();

  if (!session) {
    return (
      <>
        <Head>
          <title>Publish Events</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <meta name="robots" content="noindex"></meta>
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <h1>Publish events</h1>
        <div>You need to be authenticated to view this page.</div>
      </>
    );
  }

  if (session.user.role === "editor") {
    return (
      <>
        <Head>
          <title>Publish Events</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <meta name="robots" content="noindex"></meta>
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <h1>Publish events</h1>
        <div>You need to be authenticated to view this page.</div>
      </>
    );
  }

  return (
    <>
      <Head>
        <title>Publish Some Events there..</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="robots" content="noindex"></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="bg-slate-100">
        <div className="mx-4 lg:mx-auto mt-48 max-w-5xl">
          <h1 className="text-4xl pb-8">All Events</h1>
          <main className="lg:grid lg:grid-cols-3 lg:gap-4">
            {props.drafts.map((event) => (
              <div
                key={event.id}
                className="mb-4 lg:mb-0 rounded border border-gray-100 bg-slate-50"
              >
                <Event event={event} />
                <div className="p-2 shadow-inner">
                  {!event.published && (
                    <button
                      className="mb-2 lg:mb-0 mr-2 inline-flex w-full justify-center rounded-md border border-transparent bg-sky-600 px-2 py-1 text-white shadow-sm hover:bg-sky-700  focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2 sm:w-auto sm:text-sm"
                      onClick={() => publishPost(event.id)}
                    >
                      Publish
                    </button>
                  )}

                  <button
                    className="inline-flex mr-2 w-full justify-center rounded-md border border-transparent bg-red-600 px-2 py-1 text-white shadow-sm hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2 sm:w-auto sm:text-sm"
                    onClick={() => deletePost(event.id)}
                  >
                    Delete
                  </button>
                  <Link
                    className="mb-2 lg:mb-0 inline-flex w-full justify-center rounded-md border border-transparent bg-slate-200 px-2 py-1 text-black shadow-sm hover:bg-slate-300 sm:mr-4 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2 sm:w-auto sm:text-sm"
                    href={{
                      pathname: "/update-event",
                      query: event,
                    }}
                  >
                    Update
                  </Link>
                  <button
                    className="inline-flex mr-2 w-full justify-center rounded-md border border-transparent bg-slate-200 px-2 py-1 text-black shadow-sm hover:bg-slate-300 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2 sm:w-auto sm:text-sm"
                    onClick={() => duplicateEvent(event)}
                  >
                    Duplicate
                  </button>
                </div>
              </div>
            ))}
          </main>
          <br />
          <br />
          <br />
          <br />
        </div>
      </div>
      <style jsx>{`
        .post {
          background: var(--geist-background);
          transition: box-shadow 0.1s ease-in;
        }

        .post:hover {
          box-shadow: 1px 1px 3px #aaa;
        }

        .post + .post {
          margin-top: 2rem;
        }
      `}</style>
    </>
  );
};

export default Drafts;
